// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NorthWindContactsCodeFirst.Models
{
    public partial class Contact
    {
        public int ContactId { get; set; }
        public  string FirstName { get; set; }
        public  string LastName { get; set; }
    }
}